---
output: 
  html_document:
    css: ["css/details_summary.css", "css/style.css"]
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, results='asis'}

spcr_make_report_title_block(
  title = title,
  report_ref = report_ref,
  data_cutoff_dttm = data_cutoff_dttm,
  subtitle = subtitle,
  logo_path = logo_path,
  department = department,
  department_text_colour = department_text_colour
)

```

`r intro`

**Notes:**  
A key explaining how to read the icons for Variation, Assurance, and Data Quality is at the [bottom of this document.](#icon-key)

```{r echo=FALSE, fig.height=4, fig.width=7, message=FALSE, results='asis'}

# add the header bar
spcr_add_header_bar()

# build the report accordions row by row
purrr::pwalk(data_bundle, spcr_render_accordion)

```

---

<!-- HTML to render the dropdown containing the icon key -->
<details>
  <summary>
    <h4 class = "outer_flex" id="icon-key" style = "justify-content: flex-start">
    How to read the icons used in this document
    </h4>
  </summary>
  <div class = "details_content">
    `r spcr_icon_key_explanation()`
  </div>
</details>

---

<!-- Footer -->
Report reference:  `r report_ref`  
Report author:  `r author_name` [`r author_email`](`r paste0("mailto:", author_email, "?subject=Report ", report_ref, "...")`)  

END  
